# Generated by Django 4.1.7 on 2023-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_estudiantes_profesor_alter_curso_camada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
